[book]
authors = ["暮月"]
language = "zh"
multilingual = false
src = "src"
title = "泛函分析基础：学习指导和习题详解"

[output.html]
fold = { enable = true }
git-repository-url = "https://github.com/duskmoon314/THU_BFA"
edit-url-template = "https://github.com/duskmoon314/THU_BFA/edit/main/{path}"

[preprocessor.katex]
after = ["links"]
